// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace HoneyWell_API_Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Status of APIs", Description="\t\tIn order to check the status code of the api", SourceFile="Features\\APIStatus.feature", SourceLine=0)]
    public partial class StatusOfAPIsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "APIStatus.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Status of APIs", "\t\tIn order to check the status code of the api", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void StatusCodeOfAPIRequest(string type, string url, string status_Code, string username, string password, string grant_Type, string param, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Api"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Status Code of API Request", @__tags);
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
testRunner.Given(string.Format("The credentials for \"{0}\" type are \"{1}\", \"{2}\" and \"{3}\"", type, username, password, grant_Type), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
testRunner.And(string.Format("I want to know the Status Code of the api with \"{0}\" and \"{1}\"", type, url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
testRunner.When("I hit the request on the api", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
testRunner.Then(string.Format("the system should return {0}", status_Code), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Status Code of API Request, Variant 0", new string[] {
                "Api"}, SourceLine=11)]
        public virtual void StatusCodeOfAPIRequest_Variant0()
        {
#line 5
this.StatusCodeOfAPIRequest("Post", "https://harmandealersdev.azurewebsites.net/api/v1/users/authenticate", "200", "sandeep.vijayakumar@harman.com", "QWRpdGkwMSo=", "password", "", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Status Code of API Request, Variant 1", new string[] {
                "Api"}, SourceLine=11)]
        public virtual void StatusCodeOfAPIRequest_Variant1()
        {
#line 5
this.StatusCodeOfAPIRequest("Post", "https://harmandealersdev.azurewebsites.net/api/v1/users/authenticate", "200", "Sonal.Tantuvay@harman.com", "QWRpdGkwMSo=", "password", "", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Status Code of API Request, Variant 2", new string[] {
                "Api"}, SourceLine=11)]
        public virtual void StatusCodeOfAPIRequest_Variant2()
        {
#line 5
this.StatusCodeOfAPIRequest("Post", "https://harmandealersdev.azurewebsites.net/api/v1/users/authenticate", "200", "Seema.Joshi6@harman.com", "QWRpdGkwMSo=", "password", "", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Status Code of API Request, Variant 3", new string[] {
                "Api"}, SourceLine=11)]
        public virtual void StatusCodeOfAPIRequest_Variant3()
        {
#line 5
this.StatusCodeOfAPIRequest("Post", "https://harmandealersdev.azurewebsites.net/api/v1/users/authenticate", "200", "Mahalakshmi.Subramanian@harman.com", "QWRpdGkwMSo=", "password", "", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Status Code of API Request, Variant 4", new string[] {
                "Api"}, SourceLine=11)]
        public virtual void StatusCodeOfAPIRequest_Variant4()
        {
#line 5
this.StatusCodeOfAPIRequest("Post", "https://harmandealersdev.azurewebsites.net/api/v1/users/authenticate", "200", "Saifulla.Moka@harman.com", "SGFybWFuQDEyMw==", "password", "", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Status Code of API Request, Variant 5", new string[] {
                "Api"}, SourceLine=11)]
        public virtual void StatusCodeOfAPIRequest_Variant5()
        {
#line 5
this.StatusCodeOfAPIRequest("Get", "http://harmandealershipadminservices.azurewebsites.net/api/v1/Dealers", "200", "", "", "", "", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
